sudo: false
language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
script:
- pylint sentry setup.py
deploy:
  provider: pypi
  user: leonsp@ca.ibm.com
  password:
    secure: nTlzN/QjTqDQwSZDmbDEBS3WVUcMMMf7zzsIQPiJj5ZAyYUebqcZojx6444zCOrRlSJ5NfeV1us6VCzcTddx1wCTgqpEMSzbW0GBObvHerArM174YeWiC2PwhDe85bE1X0OOeJ5iqKQPBPtna4dcIkrRRGfyS911L1zDAyALMJDvFeKvj/SxywLv+IDsph13L2uTnESBdba79pWfjNqd4n/igKcBJ3IkJ0X7vaI2PrsgP+oL2o6lBJVYp8dY75UtyisCRPipdH9kLztT8Ohh6Bzv17ikDKPkwziwGmD+UapVNqk2huK4Tn3J39qWz5y/5mo1Ce9OCLMYpfQUb1xcToF/xWVHXTbqHz4uXowfvv8FWsldTinW8OAIJJj1yLag9WAtnkayZd9RiCgITShOt3uPj4S7SlrDOoitmHq9MfZqJH73SOK8koR+6JA13ANVdZcfWyvkcXMaQgOsh8h0bsXELMv6huVdnfMtsMrbXp7SqJU6CA8rc15qpge7/bk7RrQkZ+3dOBE4Eh7DdTEhAdHq0DF5GRiLiOgLM24dBYS+0ZewcEza1A7vQKk8s2WtWXVlF7rLxMVbEPVHwoa8jb1WFK2c1zG/XQxzbUIRXjAMHilksJZ+ZeRvWlmed7PZofPzrjJZlaEUxk6T6JuZV2T4mokHzdkw+1CSQn2pxPM=
  server: https://na.artifactory.swg-devops.com/artifactory/api/pypi/apset-pypi-local
  on:
    python: '2.7'
    tags: true
notifications:
  slack:
    secure: MwvwYkKhmAmOOUnS2anfe9Kvln0zADJmQutQ+dHlDHPlIVWwDdhQJ2n9VoVNXxXIb3i/Pv8wYrWURK48tnW+D+k3c84pKWIPWNvshHO5C1AY9wRs+XnQlF2swNmzi/MieYT3sa8LnxiHe+O23G1YJhmLn0xghAvI0IeD28nkCwlS442oInOv85CJDBR+E4dyynKi7DNyF5zFPj2hA08h6fZsl6gqqo43E09O9XIvrQLCZREmhneQXNbs0zz/29K2v0IPTd3sK/TlyqkvkyY2aQ/3OyS+DCzG+/87HC0c29749Si2fdrBSMI66Q77R1brQ5aHf9ybV5atn/ilv1zsi4glaqZBdUk4412cl85mVo5L37+FPsh0Uuq4WrAsH7fXUyWno+WgozyRDymXJFiI8Uee7ofVn128h5C/4uFNredC3LLj3Q+GPLwOBMXrigwnCsIvZxP/4vIfRtb1EfPFtbTDu2n8GGothWQ62NewNQ4g+1G4fVUHuhbdQ4rzJrWW/ZmNLzEH/jOQviG5LkUU9JKwZUOmJYQkj9mXmPzf+4QcNBbkGYvSv0kxLtzCZw+oMmGwdZplJu7Uxr0Q5QQc68d+KUwbCYULR3meqZnAQ4TTSuzq+H9oRtO95CVwhkYGkcP8tRGxHB5toqCaJF3PJdpie6tcaBiXmhKOhVPCyQA=
